# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'db/migrate/20240830111252_devise_token_auth_create_users.rb'
    - 'config/initializers/devise.rb'
